#ifndef TCPIP_NETWORK_CONSTANTS_H
#define TCPIP_NETWORK_CONSTANTS_H

// Mac ADDRESS
#define BROADCAST_MAC_ADDRESS 0xFFFFFFFFFFFF
#define MAC_ADDRESS_SIZE 6

// IPV4
#define IPV4_ADDRESS_SIZE 4
#define IPV4_ADDRESS_STRING_SIZE 16
#define IPV4_PROTOCOL_ID 0x0800


// IPV6
#define IPV6_ADDRESS_SIZE 16
#define IPV6_PROTOCOL_ID 0x08DD

// ETHERNET
#define MAX_ETHERNET_SIZE 1518
#define ETHERNET_PREAMBLE_SIZE 7
#define ETHERNET_SFD_SIZE 1
#define ETHERNET_TYPE_SIZE 2
#define ETHERNET_CRC_SIZE 4
#define ETHERNET_MAX_PAYLOAD_SIZE 1500 // Maximum payload size

// ARP CONSTANTS VALUE
#define ARP_HARDWARE_TYPE_ETH 1
#define ARP_OPERATION_REQUEST 1
#define ARP_OPERATION_REPLY 2
#define ARP_MESSAGE_PROTOCOL_ID 0x806

// ARP SIZE
#define ARP_HEADER_SIZE 28
#define ARP_HARDWARE_TYPE_SIZE 2
#define ARP_PROTOCOL_TYPE_SIZE 2
#define ARP_HARDWARE_ADDRESS_LENGTH_SIZE 1
#define ARP_PROTOCOL_ADDRESS_LENGTH_SIZE 1
#define ARP_OPERATION_CODE_SIZE 2
#endif // TCPIP_NETWORK_CONSTANTS_H
